#!/usr/bin/env perl
use strict;
use warnings;

use Music::Percussion::Tabla ();

my $bars = shift || 4;
my $bpm  = shift || 120;

my $tabla = Music::Percussion::Tabla->new(
    file    => "$0.mid",
    bpm     => $bpm,
    channel => 0,
    volume  => 127,
    verbose => 1,
);
#warn __PACKAGE__,' L',__LINE__,' ',$tabla->soundfont,"\n";

for my $i (1 .. $tabla->bars) {
    $tabla->tun;
}

for my $i (1 .. $tabla->bars) {
    $tabla->ta;
}

for my $i (1 .. $tabla->bars) {
    $tabla->tin;
}

for my $i (1 .. $tabla->bars) {
    $tabla->tu;
}

for my $i (1 .. $tabla->bars) {
    $tabla->te;
}

for my $i (1 .. $tabla->bars) {
    $tabla->tete;
}

for my $i (1 .. $tabla->bars) {
    $tabla->ka;
}

for my $i (1 .. $tabla->bars) {
    $tabla->ga;
}

for my $i (1 .. $tabla->bars) {
    $tabla->ga_slide;
}

for my $i (1 .. $tabla->bars) {
    $tabla->dha;
}

for my $i (1 .. $tabla->bars) {
    $tabla->dhin;
}

for my $i (1 .. $tabla->bars) {
    $tabla->tirkit;
}

$tabla->write;
