#!/usr/bin/env perl
use strict;
use warnings;

use Music::Percussion::Tabla ();

my $bpm  = shift || 120;

my $tabla = Music::Percussion::Tabla->new(
    file    => "$0.mid",
    bpm     => $bpm,
    channel => 0,
    volume  => 127,
    verbose => 1,
);
#warn __PACKAGE__,' L',__LINE__,' ',$tabla->soundfont,"\n";

# bol practice
$tabla->tun;
$tabla->rest($tabla->quarter);
$tabla->ta;
$tabla->tun;
$tabla->tin;
$tabla->tin;
$tabla->tun;
$tabla->ta;
$tabla->te;
$tabla->te;
$tabla->ta;
$tabla->tun;
$tabla->ta;
$tabla->tun;
$tabla->ta;
$tabla->tun;
$tabla->tun;
$tabla->tin;
$tabla->tin;
$tabla->ta;
$tabla->ta;
$tabla->rest($tabla->whole);

$tabla->ta;
$tabla->tun;
$tabla->tun;
$tabla->ta;
$tabla->ta;
$tabla->tun;
$tabla->tun;
$tabla->ta;
$tabla->ta;
$tabla->te;
$tabla->te;
$tabla->ta;
$tabla->ta;
$tabla->tin;
$tabla->tin;
$tabla->ta;
$tabla->rest($tabla->whole);

for my $i (1 .. $tabla->beats) {
    $tabla->tun;
}
for my $i (1 .. $tabla->beats) {
    $tabla->ta;
}
for my $i (1 .. $tabla->beats) {
    $tabla->tin;
}
for my $i (1 .. $tabla->beats) {
    $tabla->tu;
}
for my $i (1 .. $tabla->beats) {
    $tabla->te;
}
for my $i (1 .. $tabla->beats) {
    $tabla->tete;
}
for my $i (1 .. $tabla->beats) {
    $tabla->ka;
}
for my $i (1 .. $tabla->beats) {
    $tabla->ga;
}
for my $i (1 .. $tabla->beats) {
    $tabla->ga_slide;
}
for my $i (1 .. $tabla->beats) {
    $tabla->dha;
}
for my $i (1 .. $tabla->beats) {
    $tabla->dhin;
}
for my $i (1 .. $tabla->beats) {
    $tabla->tirkit;
}

$tabla->write;
